[deploy]
name = "default"

[aws]
region = "us-east-1"

[s3]
bucket_name = "bpkio-cs-demos"
folder = "fabre/ts-files-with-scte"          # prefix inside the bucket, e.g. "media/ts" — leave empty for root

[input]
ts_file = "../output_with_markers_test.ts"
