output:
  file: ../outputs/break-and-popos.ts
  resolution: "1920x1080"
  framerate: 25
  bitrate_kbps: 10000
  gop: 50
  service_provider: "broadpeak"
  service_name: "broadpeak.io"

normalize: true
slate_image: /Users/fabrelambeau/Broadpeak/Resources/Backgrounds/testing-slate.png

assets:
  # First asset
  
  - file: /Users/fabrelambeau/Broadpeak/Code/prepare-asset-ts-scte35/example/asset1.mp4
    duration: "1 min"
    countdown: 10
    fade_out: 1.5

  # Linear ad (0x0C)
  
  - file: '/Users/fabrelambeau/Downloads/Lambrini Advert.mp4'
    duration: "30s"
    countdown: 10
    ad_break:
      event_id: 1
      splice_type: time_signal
      segmentation:
        type_id: "0x34"
        upid_type: "0x0C"
        upid_hex: "5349474E414C3A4C494E454152"
        web_delivery_allowed: true
        no_regional_blackout: false
        archive_allowed: false
        device_restrictions: 1

  - file: /Users/fabrelambeau/Broadpeak/Code/prepare-asset-ts-scte35/example/asset1.mp4
    start: "60s"
    duration: "30s"
    countdown: 10
    fade_in: 1.5
    fade_out: 1.5

  # Second asset, containing a 0x38 marker
  
  - file: /Users/fabrelambeau/Broadpeak/Code/prepare-asset-ts-scte35/example/asset2.mp4
    fade_in: 1
    duration: "30s"
    countdown: 10    
  
  - file: /Users/fabrelambeau/Broadpeak/Code/prepare-asset-ts-scte35/example/asset2.mp4
    start: "30s"
    duration: "20s"
    countdown: 10
    ad_break:
      event_id: 20
      splice_type: time_signal
      segmentation:
        type_id: "0x38"
        upid_type: "0x0C"
        upid_hex: "5349474E414C3A4E4F4E4C494E454152"
        web_delivery_allowed: true
        no_regional_blackout: false
        archive_allowed: false
        device_restrictions: 1

  - file: /Users/fabrelambeau/Broadpeak/Code/prepare-asset-ts-scte35/example/asset2.mp4
    start: "50s"
    duration: "30s"
    countdown: 10
    fade_out: 2
